updated zigbuild

diff --git a/bin/zig-run b/bin/zig-run
--- a/bin/zig-run
+++ b/bin/zig-run
@@ -1,5 +1,8 @@
 #!/bin/bash
 #--------------------------------------------------------------------------------
+match_libc() { grep -qE '@?cImport|@c(Include|Define|Undef|Struct|Union)|\bstd\.c\b|@import\("std"\)\.c' "$1"; }
+LC=""
+#--------------------------------------------------------------------------------
 #################################################################################
 #--------------------------------------------------------------------------------
 [ "${ZIG_BUILD_MODE}" == "" ] && ZIG_BUILD_MODE="ReleaseSmall"
@@ -14,44 +17,92 @@ SOURCE=""
 #--------------------------------------------------------------------------------
 #################################################################################
 #--------------------------------------------------------------------------------
-if [ -f "Taskfile.yml" ] || [ -f "Taskfile.yaml" ] || [ -f "taskfile.yml" ] || [ -f "taskfile.yaml" ]
+if [ "${1}" == "." ] || [ "${1}" == "*" ] || [ "${1}" == "all" ]
 then
 	#----------------------------------------
-	task run -- ${*}
+	shift
 	#----------------------------------------
-	exit $?
-	#----------------------------------------
-elif [ -f "Makefile" ] || [ -f "makefile" ]
+	for FILENAME in *.zig
+	do
+		#----------------------------------------
+		if [ -f "${FILENAME}" ]
+		then
+			#----------------------------------------
+			match_libc ${FiLENAME} && LC="-lc"
+			#----------------------------------------
+			echo "${FILENAME}:"
+			zig run ${FILENAME} ${LC} -O ${ZIG_BUILD_MODE} -- ${*}
+			echo
+			#----------------------------------------
+		fi
+		#----------------------------------------
+	done
+	#--------------------------------------------------------------------------------
+	exit 0
+	#--------------------------------------------------------------------------------
+elif [ "${1}" != "" ]
 then
 	#----------------------------------------
-	make run ARGS="${*}"
-	#----------------------------------------
-	exit $?
-	#----------------------------------------
-elif [ -f "main.zig" ]
-then
-	#----------------------------------------
-	SOURCE="main.zig"
-	#----------------------------------------
-elif [ -f "root.zig" ]
-then
-	#----------------------------------------
-	SOURCE="root.zig"
-	#----------------------------------------
-else
-	#----------------------------------------
-	if [ -f "${BASENAME}.zig" ]
+	if [ -f "${1}" ]
 	then
 		#----------------------------------------
-		SOURCE="${BASENAME}.zig"
+		SOURCE=${1}; shift
+		#----------------------------------------
+		match_libc ${SOURCE} && LC="-lc"
+		#----------------------------------------
+		zig run ${SOURCE} ${LC} -O ${ZIG_BUILD_MODE} -- ${*}
 		#----------------------------------------
 	else
 		#----------------------------------------
-		echo "unknown source filename"
+		echo "invalid source filename: ${SOURCE}"
 		exit 1
 		#----------------------------------------
 	fi
-	#----------------------------------------
+	#--------------------------------------------------------------------------------
+	exit $?
+	#--------------------------------------------------------------------------------
+else
+	#--------------------------------------------------------------------------------
+	if [ -f "Taskfile.yml" ] || [ -f "Taskfile.yaml" ] || [ -f "taskfile.yml" ] || [ -f "taskfile.yaml" ]
+	then
+		#----------------------------------------
+		task run -- ${*}
+		#----------------------------------------
+		exit $?
+		#----------------------------------------
+	elif [ -f "Makefile" ] || [ -f "makefile" ]
+	then
+		#----------------------------------------
+		make run ARGS="${*}"
+		#----------------------------------------
+		exit $?
+		#----------------------------------------
+	elif [ -f "main.zig" ]
+	then
+		#----------------------------------------
+		SOURCE="main.zig"
+		#----------------------------------------
+	elif [ -f "root.zig" ]
+	then
+		#----------------------------------------
+		SOURCE="root.zig"
+		#----------------------------------------
+	else
+		#----------------------------------------
+		if [ -f "${BASENAME}.zig" ]
+		then
+			#----------------------------------------
+			SOURCE="${BASENAME}.zig"
+			#----------------------------------------
+		else
+			#----------------------------------------
+			echo "unknown source filename"
+			exit 1
+			#----------------------------------------
+		fi
+		#----------------------------------------
+	fi
+	#--------------------------------------------------------------------------------
 fi
 #--------------------------------------------------------------------------------
 #################################################################################
@@ -59,13 +110,17 @@ fi
 if [ -f "${SOURCE}" ]
 then
 	#----------------------------------------
-	zig run ${SOURCE} -O ${ZIG_BUILD_MODE} -- ${*}
+	match_libc ${SOURCE} && LC="-lc"
+	#----------------------------------------
+	zig run ${SOURCE} ${LC} -O ${ZIG_BUILD_MODE} -- ${*}
 	#----------------------------------------
 else
 	#----------------------------------------
 	echo "unknown source filename"
 	#----------------------------------------
 fi
+#--------------------------------------------------------------------------------
+exit $?
 #--------------------------------------------------------------------------------
 #################################################################################
 #--------------------------------------------------------------------------------
diff --git a/bin/zig-test b/bin/zig-test
--- a/bin/zig-test
+++ b/bin/zig-test
@@ -1,50 +1,126 @@
 #!/bin/bash
 #--------------------------------------------------------------------------------
+match_libc() { grep -qE '@?cImport|@c(Include|Define|Undef|Struct|Union)|\bstd\.c\b|@import\("std"\)\.c' "$1"; }
+LC=""
+#--------------------------------------------------------------------------------
 #################################################################################
 #--------------------------------------------------------------------------------
-if [ "${1}" != "" ] && [ -f "${1}" ]
-then
-	#----------------------------------------
-	zig test ${1} -Doptimize=Debug
-	#----------------------------------------
-elif [ -f "run-tests" ]
-then
-	#----------------------------------------
-	/bin/bash run-tests ${*}
-	exit $?
-	#----------------------------------------
-elif [ "${1}" == "" ] && [ -f "tests.zig" ]
-then
-	#----------------------------------------
-	zig test tests.zig -Doptimize=Debug
-	#----------------------------------------
-elif [ "${1}" == "" ] && [ -f "main.zig" ]
-then
-	#----------------------------------------
-	zig test main.zig -Doptimize=Debug
-	#----------------------------------------
-elif [ "${1}" == "" ] && [ -f "root.zig" ]
-then
-	#----------------------------------------
-	zig test root.zig -Doptimize=Debug
-	#----------------------------------------
-elif [ "${1}" == "all" ]
+if [ "${1}" == "." ] || [ "${1}" == "*" ] || [ "${1}" == "all" ]
 then
 	#----------------------------------------
 	for FILENAME in *.zig
 	do
 		#----------------------------------------
-		if [ -f "$FILENAME" ]
+		if [ -f "${FILENAME}" ]
 		then
 			#----------------------------------------
 			echo "${FILENAME}:"
-			zig test ${FILENAME} -Doptimize=Debug
+			#----------------------------------------
+			if [ "${FILENAME}" == "run-tests.zig" ]
+			then
+				#----------------------------------------
+				match_libc ${FILENAME} && LC="-lc"
+				#----------------------------------------
+				zig run ${FILENAME} ${LC} -O ${ZIG_BUILD_MODE}
+				#----------------------------------------
+			else
+				#----------------------------------------
+				zig test ${FILENAME} -Doptimize=Debug
+				#----------------------------------------
+			fi
+			#----------------------------------------
 			echo
 			#----------------------------------------
 		fi
 		#----------------------------------------
 	done
+	#--------------------------------------------------------------------------------
+	exit 0
+	#--------------------------------------------------------------------------------
+fi
+#--------------------------------------------------------------------------------
+#################################################################################
+#--------------------------------------------------------------------------------
+if [ "${1}" != "" ]
+then
 	#----------------------------------------
+	for FILENAME in "$@"
+    do
+        if [ -f "${FILENAME}" ]
+        then
+			#----------------------------------------
+            echo "${FILENAME}:"
+            zig test "${FILENAME}" -Doptimize=Debug
+            echo
+			#----------------------------------------
+		elif [ "${FILENAME}" == "run-tests.zig" ]
+		then
+			#----------------------------------------
+			match_libc run-tests.zig && LC="-lc"
+			#----------------------------------------
+			zig run run-tests.zig ${LC} -O ${ZIG_BUILD_MODE}
+			#----------------------------------------
+        elif [ -f "${FILENAME}.zig" ]
+        then
+			#----------------------------------------
+            echo "${FILENAME}.zig:"
+            zig test "${FILENAME}.zig" -Doptimize=Debug
+            echo
+			#----------------------------------------
+        else
+			#----------------------------------------
+			echo "invalid source filename: ${FILENAME}"
+			exit 1
+			#----------------------------------------
+		fi
+    done
+	#--------------------------------------------------------------------------------
+	exit 0
+	#--------------------------------------------------------------------------------
+else
+	#--------------------------------------------------------------------------------
+	# check for zig files (may be used later)
+	#--------------------------------------------------------------------------------
+	ZIG_FILE_COUNT=$(ls *.zig 2>/dev/null | wc -l)
+	#--------------------------------------------------------------------------------
+	if [ -f "run-tests" ]
+	then
+		#----------------------------------------
+		/bin/bash run-tests ${*}
+		#----------------------------------------
+	elif [ -f "run-tests.zig" ]
+	then
+		#----------------------------------------
+		match_libc run-tests.zig && LC="-lc"
+		#----------------------------------------
+		zig run run-tests.zig ${LC} -O ${ZIG_BUILD_MODE}
+		#----------------------------------------
+	elif [ "${ZIG_FILE_COUNT}" -gt 0 ]
+	then
+		#----------------------------------------
+		for FILENAME in *.zig
+		do
+			#----------------------------------------
+			if [ -f "${FILENAME}" ]
+			then
+				#----------------------------------------
+				echo "${FILENAME}"
+				zig test ${FILENAME} -Doptimize=Debug
+	            echo
+				#----------------------------------------
+			fi
+			#----------------------------------------
+		done
+		#----------------------------------------
+	else
+		#----------------------------------------
+		echo "no zig files found in current directory"
+		exit 1
+		#----------------------------------------
+	fi
+	#--------------------------------------------------------------------------------
+	exit $?
+	#--------------------------------------------------------------------------------
 fi
 #--------------------------------------------------------------------------------
 #################################################################################
diff --git a/bin/zigbuild b/bin/zigbuild
--- a/bin/zigbuild
+++ b/bin/zigbuild
@@ -1,5 +1,8 @@
 #!/bin/bash
 #--------------------------------------------------------------------------------
+match_libc() { grep -qE '@?cImport|@c(Include|Define|Undef|Struct|Union)|\bstd\.c\b|@import\("std"\)\.c' "$1"; }
+LC=""
+#--------------------------------------------------------------------------------
 #################################################################################
 #--------------------------------------------------------------------------------
 source $(dirname ${BASH_SOURCE[0]})/zigbuild-env-vars
@@ -13,81 +16,131 @@ DIRECTORY=$(pwd); BASENAME=$(basename "$(pwd)")
 #--------------------------------------------------------------------------------
 ZIG_FILE_COUNT=$(find . -type f -name "*.zig" | wc -l)
 #--------------------------------------------------------------------------------
-OUTPUT=${BASENAME}; OUTPUT_PATH="zig-out"
-#--------------------------------------------------------------------------------
-SOURCE=""
+SOURCE=""; OUTPUT=${BASENAME}; OUTPUT_PATH="zig-out"
 #--------------------------------------------------------------------------------
 #################################################################################
 #--------------------------------------------------------------------------------
-if [ -f "Taskfile.yml" ] || [ -f "Taskfile.yaml" ] || [ -f "taskfile.yml" ] || [ -f "taskfile.yaml" ]
+if [ "${1}" == "." ] || [ "${1}" == "*" ] || [ "${1}" == "all" ]
 then
-	#----------------------------------------
-	task build
-	#----------------------------------------
-	exit $?
-	#----------------------------------------
-elif [ -f "Makefile" ] || [ -f "makefile" ]
+	#--------------------------------------------------------------------------------
+	shift
+	#--------------------------------------------------------------------------------
+	for FILENAME in *.zig
+	do
+		#----------------------------------------
+		if [ -f "${FILENAME}" ]
+		then
+			#----------------------------------------
+			echo "${FILENAME}:"
+			$(dirname ${BASH_SOURCE[0]})/zigbuild ${FILENAME} ${*}
+			echo
+			#----------------------------------------
+		fi
+		#----------------------------------------
+	done
+	#--------------------------------------------------------------------------------
+	exit 0
+	#--------------------------------------------------------------------------------
+elif [ "${1}" != "" ]
 then
-	#----------------------------------------
-	make build
-	#----------------------------------------
-	exit $?
-	#----------------------------------------
-elif [ -f "build.zig" ]
-then
-	#----------------------------------------
-	zig build -Doptimize=${ZIG_BUILD_MODE} -Dtarget=${ZIG_BUILD_TARGET} -Dcpu=${ZIG_BUILD_CPU}
-	#----------------------------------------
-	exit $?
-	#----------------------------------------
-elif [ "${ZIG_FILE_COUNT}" -eq 2 ] && [ -f "root.zig" ] && [ -f "main.zig" ]
-then
-	#----------------------------------------
-	mkdir -p ${OUTPUT_PATH}; cd ${OUTPUT_PATH}
-	#----------------------------------------
-	zig build-lib ../root.zig -femit-bin=lib${OUTPUT}.a ${FSTRIP} -static -O ${ZIG_BUILD_MODE}
-	[ $? -eq 0 ] && zig build-exe ../main.zig -femit-bin=${OUTPUT} -L. -l${OUTPUT} ${FSTRIP} -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU}
-	exit $?
-	#----------------------------------------
-elif [ "${ZIG_FILE_COUNT}" -eq 1 ] && [ -f "root.zig" ]
-then
-	#----------------------------------------
-	SOURCE="root.zig"
-	#----------------------------------------
-elif [ -f "main.zig" ]
-then
-	#----------------------------------------
-	SOURCE="main.zig"
-	#----------------------------------------
+	#--------------------------------------------------------------------------------
+	if [ -f "${1}" ]
+	then
+		SOURCE=${1}
+	elif [ -f "${1}.zig" ]
+	then
+		SOURCE=${1}.zig
+	else
+		echo "invalid source filename: ${FILENAME}"
+		exit 1
+	fi
+	#--------------------------------------------------------------------------------
+	shift
+	#--------------------------------------------------------------------------------
 else
-	#----------------------------------------
-	if [ -f "${BASENAME}.zig" ]
+	#--------------------------------------------------------------------------------
+	if [ -f "Taskfile.yml" ] || [ -f "Taskfile.yaml" ] || [ -f "taskfile.yml" ] || [ -f "taskfile.yaml" ]
 	then
 		#----------------------------------------
-		SOURCE="${BASENAME}.zig"
+		task build
+		#----------------------------------------
+		exit $?
+		#----------------------------------------
+	elif [ -f "Makefile" ] || [ -f "makefile" ]
+	then
+		#----------------------------------------
+		make build
+		#----------------------------------------
+		exit $?
+		#----------------------------------------
+	elif [ -f "build.zig" ]
+	then
+		#----------------------------------------
+		zig build -Doptimize=${ZIG_BUILD_MODE} -Dtarget=${ZIG_BUILD_TARGET} -Dcpu=${ZIG_BUILD_CPU}
+		#----------------------------------------
+		exit $?
+		#----------------------------------------
+	elif [ "${ZIG_FILE_COUNT}" -eq 2 ] && [ -f "root.zig" ] && [ -f "main.zig" ]
+	then
+		#----------------------------------------
+		LC_ROOT=""; LC_MAIN=""
+		match_libc root.zig && LC_ROOT="-lc"
+		match_libc main.zig && LC_MAIN="-lc"
+		#--------------------------------------------------------------------------------
+		mkdir -p ${OUTPUT_PATH}; cd ${OUTPUT_PATH}
+		#----------------------------------------
+		zig build-lib ../root.zig -femit-bin=lib${OUTPUT}.a ${LC} ${FSTRIP} -static -O ${ZIG_BUILD_MODE}
+		[ $? -eq 0 ] && zig build-exe ../main.zig -femit-bin=${OUTPUT} -L. -l${OUTPUT} ${LC} ${FSTRIP} -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU}
+		exit $?
+		#----------------------------------------
+	elif [ "${ZIG_FILE_COUNT}" -eq 1 ] && [ -f "root.zig" ]
+	then
+		#----------------------------------------
+		SOURCE="root.zig"
+		#----------------------------------------
+	elif [ -f "main.zig" ]
+	then
+		#----------------------------------------
+		SOURCE="main.zig"
 		#----------------------------------------
 	else
 		#----------------------------------------
-		echo "unknown source filename"
-		exit 1
+		if [ -f "${BASENAME}.zig" ]
+		then
+			#----------------------------------------
+			SOURCE="${BASENAME}.zig"
+			#----------------------------------------
+		else
+			#----------------------------------------
+			echo "unknown source filename"
+			exit 1
+			#----------------------------------------
+		fi
 		#----------------------------------------
 	fi
-	#----------------------------------------
+	#--------------------------------------------------------------------------------
 fi
 #--------------------------------------------------------------------------------
 #################################################################################
+#--------------------------------------------------------------------------------
+match_libc ${SOURCE} && LC="-lc"
 #--------------------------------------------------------------------------------
 mkdir -p ${OUTPUT_PATH}; cd ${OUTPUT_PATH}
 #--------------------------------------------------------------------------------
 if [ "${SOURCE}" == "root.zig" ]
 then
 	#----------------------------------------
-	zig build-lib ../${SOURCE} -femit-bin=lib${OUTPUT}.so ${FSTRIP} -dynamic -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU}
-	zig build-lib ../${SOURCE} -femit-bin=lib${OUTPUT}.a ${FSTRIP} -static -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU}
+	zig build-lib ../${SOURCE} -femit-bin=lib${OUTPUT}.so ${LC} ${FSTRIP} -dynamic -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU}
+	zig build-lib ../${SOURCE} -femit-bin=lib${OUTPUT}.a ${LC} ${FSTRIP} -static -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU}
 	#----------------------------------------
 else
 	#----------------------------------------
-	zig build-exe ../${SOURCE} -femit-bin=${OUTPUT} ${FSTRIP} -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU}
+	if [ "${SOURCE}" == "main.zig" ]
+	then
+		zig build-exe ../${SOURCE} -femit-bin=${OUTPUT} ${LC} ${FSTRIP} -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU} ${*}
+	else
+		zig build-exe ../${SOURCE} -femit-bin=${SOURCE%.zig} ${LC} ${FSTRIP} -O ${ZIG_BUILD_MODE} -target ${ZIG_BUILD_TARGET} -mcpu=${ZIG_BUILD_CPU} ${*}
+	fi
 	#----------------------------------------
 fi
 #--------------------------------------------------------------------------------
diff --git a/bin/zigbuild-run b/bin/zigbuild-run
--- a/bin/zigbuild-run
+++ b/bin/zigbuild-run
@@ -4,7 +4,78 @@
 #--------------------------------------------------------------------------------
 DIRECTORY=$(pwd); BASENAME=$(basename "$(pwd)")
 #--------------------------------------------------------------------------------
-OUTPUT=${BASENAME}; OUTPUT_PATH="zig-out"
+SOURCE=""; OUTPUT=${BASENAME}; OUTPUT_PATH="zig-out"
+#--------------------------------------------------------------------------------
+#################################################################################
+#--------------------------------------------------------------------------------
+if [ "${1}" == "." ] || [ "${1}" == "*" ] || [ "${1}" == "all" ]
+then
+	#--------------------------------------------------------------------------------
+	shift
+	#--------------------------------------------------------------------------------
+	mkdir -p ${OUTPUT_PATH};
+	#--------------------------------------------------------------------------------
+	for FILENAME in *.zig
+	do
+		#----------------------------------------
+		if [ -f "${FILENAME}" ]
+		then
+			#----------------------------------------
+			echo "${FILENAME}:"
+			#----------------------------------------
+			$(dirname ${BASH_SOURCE[0]})/zigbuild ${FILENAME}
+			#----------------------------------------
+			if [ $? -eq 0 ] && [ -d "${OUTPUT_PATH}" ] && [ -f "${OUTPUT_PATH}/${OUTPUT}" ]
+			then
+				#----------------------------------------
+				cd ${OUTPUT_PATH}
+				#----------------------------------------
+				./${OUTPUT} ${*}
+				#----------------------------------------
+				cd ..
+				#----------------------------------------
+			fi
+			#----------------------------------------
+			echo
+			#----------------------------------------
+		fi
+		#----------------------------------------
+	done
+	#--------------------------------------------------------------------------------
+	exit 0
+	#--------------------------------------------------------------------------------
+elif [ "${1}" != "" ]
+then
+	#--------------------------------------------------------------------------------
+	if [ -f "${1}" ]
+	then
+		SOURCE=${1}
+	elif [ -f "${1}.zig" ]
+	then
+		SOURCE=${1}.zig
+	else
+		echo "invalid source filename: ${FILENAME}"
+		exit 1
+	fi
+	#--------------------------------------------------------------------------------
+	shift
+	#--------------------------------------------------------------------------------
+	$(dirname ${BASH_SOURCE[0]})/zigbuild ${SOURCE}
+	#----------------------------------------
+	[ "${SOURCE}" != "main.zig" ] && OUTPUT=${SOURCE%.zig}
+	#----------------------------------------
+	if [ $? -eq 0 ] && [ -d "${OUTPUT_PATH}" ] && [ -f "${OUTPUT_PATH}/${OUTPUT}" ]
+	then
+		#----------------------------------------
+		cd ${OUTPUT_PATH}
+		#----------------------------------------
+		./${OUTPUT} ${*}
+		#----------------------------------------
+	fi
+	#--------------------------------------------------------------------------------
+	exit $?
+	#--------------------------------------------------------------------------------
+fi
 #--------------------------------------------------------------------------------
 #################################################################################
 #--------------------------------------------------------------------------------
@@ -24,9 +95,9 @@ then
 	#----------------------------------------
 	exit $?
 	#----------------------------------------
-	fi
+fi
 #--------------------------------------------------------------------------------
-zigbuild
+$(dirname ${BASH_SOURCE[0]})/zigbuild
 #--------------------------------------------------------------------------------
 if [ $? -eq 0 ]
 then
